<?php
return [
    'CONSUMER_KEY' => env('CONSUMER_KEY'),
    'CONSUMER_SECRET' => env('CONSUMER_SECRET'),
    'ACCESS_TOKEN' => env('ACCESS_TOKEN'),
    'ACCESS_TOKEN_SECRET' => env('ACCESS_TOKEN_SECRET'),
];